### ISSUE TITLE
Create Grails 3.x compatible version

### ISSUE THREAD

**Issue by aruizca** [bmuschko/grails-google-visualization#49]
- [x] branch current 1.x version for Grails 2.x support
- [x] merge PR #52 on master for Grails 3.x support
- [x] Fix issues
- [x] test on Grails 3 based host app
- [x] release plugin on Bintray

**Comment by aruizca** [comment]
related to PR #52

**Comment by jonnyy** [comment]
Hey I'm in the process of upgrading an app to grails 3 now, and was wondering how the testing is coming along for this?

**Comment by aruizca** [comment]
@jonnyy Sorry I did not close this. look for 2.0 version in Bintray.

**Comment by jonnyy** [comment]
Great! Thanks, so much!
