### ISSUE TITLE
Unnecessary ‘&#39;’ tags are generated on a formatter of 'gvisualization:table'

### ISSUE THREAD

**Issue by umkis** [bmuschko/grails-google-visualization#50]
The following codes are in a GSP file for a google visualization table. 

<%
    org.grails.plugins.google.visualization.formatter.DateFormatter f = new org.grails.plugins.google.visualization.formatter.DateFormatter(2); 
    f.formatType = 'long';
%>
&lt;gvisualization:table elementId="tablechart1" allowHtml="${false}" columns="${dataColumns}" data="${dataResult}" formatters="${[f]}"/&gt;

And these codes are transformed to javascript codes as following, but have a syntax error, as you can see, ‘&amp;#39;’ are generated.

    var formatter_3 = new google.visualization.DateFormat({formatType: &#39;long&#39;});
    formatter_3.format(visualization_data, 2);

**Comment by aruizca** [comment]
What version of the plugin are you using?

**Comment by umkis** [comment]
The plugin version is 0.6.2.

**Comment by aruizca** [comment]
This issue has been fixed since version 0.7.1
Latest version is 1.0.1

**Comment by umkis** [comment]
Thank you for your advice.
