### ISSUE TITLE
UrlMappings name clash

### ISSUE THREAD

**Issue by robertoschwald** [bmuschko/grails-google-visualization#63]
In the plugin, the UrlMappings.groovy must be renamed and prefixed by the plugin name, to avoid collisions. 

Please rename UrlMappings.groovy to GrailsGoogleVisualizationUrlMappings.groovy.

See also: https://github.com/grails-profiles/web-plugin/issues/1

**Comment by aruizca** [comment]
Thanks @robertoschwald 
Would you mind sending a PR please? I would publish it gladly.
Cheers

**Comment by robertoschwald** [comment]
Will do.

**Comment by robertoschwald** [comment]
Maybe its best to remove UrlMappings.groovy completely from the plugin and leave it up to the integrators to map it, as it just holds the default mapping.

**Comment by aruizca** [comment]
Not sure if the plugin will run without a host app then. Because IIRC the plugin can run itself with the examples

**Comment by robertoschwald** [comment]
Ah ok, then I rename the mapping file.

**Comment by aruizca** [comment]
2.1.1 released with the fix. Thank you very much!
